#define yy_create_buffer aa_create_buffer
#define yy_delete_buffer aa_delete_buffer
#define yy_scan_buffer aa_scan_buffer
#define yy_scan_string aa_scan_string
#define yy_scan_bytes aa_scan_bytes
#define yy_flex_debug aa_flex_debug
#define yy_init_buffer aa_init_buffer
#define yy_flush_buffer aa_flush_buffer
#define yy_load_buffer_state aa_load_buffer_state
#define yy_switch_to_buffer aa_switch_to_buffer
#define yyin aain
#define yyleng aaleng
#define yylex aalex
#define yyout aaout
#define yyrestart aarestart
#define yytext aatext
#define yywrap aawrap

#line 20 "./FOLDER_1_LEXER_User/User_Lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.89 96/05/25 21:02:21 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 9
#define YY_END_OF_BUFFER 10
static yyconst short int yy_accept[191] =
    {   0,
        4,    4,   10,    4,    6,    4,    4,    4,    4,    4,
        8,    7,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    0,    4,    4,    4,    4,    0,    4,    4,
        4,    4,    0,    4,    4,    4,    4,    0,    4,    4,
        4,    4,    0,    4,    4,    4,    4,    0,    4,    4,
        4,    4,    0,    4,    4,    0,    4,    4,    0,    4,
        2,    4,    4,    4,    0,    4,    4,    2,    0,    2,
        4,    4,    4,    0,    4,    4,    0,    4,    4,    0,

        4,    4,    0,    4,    4,    0,    4,    4,    0,    4,
        4,    0,    4,    4,    0,    4,    4,    0,    4,    4,
        0,    4,    4,    0,    4,    4,    0,    4,    4,    0,
        4,    4,    0,    4,    4,    0,    4,    1,    4,    0,
        4,    0,    4,    4,    1,    0,    1,    4,    4,    0,
        4,    4,    0,    4,    3,    4,    0,    4,    4,    3,
        0,    3,    4,    4,    0,    4,    4,    0,    4,    4,
        0,    4,    4,    0,    4,    4,    0,    4,    4,    0,
        4,    4,    0,    4,    0,    4,    4,    0,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    1,    1,    1,    1,    1,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   12,   13,
        9,    9,   14,    9,    9,   15,    9,   16,    9,    9,
        9,    9,   17,    9,    9,    9,    9,    9,   18,    9,
        1,    1,    1,    1,   19,    1,   20,    9,   21,    9,

       22,    9,    9,    9,   23,    9,    9,    9,    9,    9,
        9,    9,    9,   24,   25,   26,   27,    9,    9,    9,
        9,   28,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[29] =
    {   0,
        1,    2,    1,    1,    3,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[216] =
    {   0,
        0,    2,  324,  302,  297,  294,    3,    4,  291,  291,
     1244, 1244,    5,    8,    6,   10,    7,   11,   15,   12,
        9,   13,   21,   30,   33,   35,   38,   36,   40,   42,
       43,   67,   44,   46,   74,   53,   47,   79,   98,   59,
       49,  103,  272,   88,  121,   61,   50,  263,  109,  139,
       93,   83,   38,  165,   91,   94,   85,   94,  191,  110,
      127,   86,  114,  215,  119,  237,  243,  115,  261,  284,
      303,  308,  258,  145,  326,  129,  150,  344,  143,  155,
      270,  362,  380,  399,  208,  170,  404, 1244,  159,  200,
      175,  430,  456,  171,  180,  474,   98,  492,  176,  181,

      518,  179,  169,  207,  544,  134,  570,  192,  199,  594,
      203,  164,  618,  204,  213,  644,  209,  233,  665,  232,
      154,  686,  231,  144,  710,  733,  241,  751,  188,  235,
      774,  245,  255,  273,  795,  262,  293,  151,  813,  264,
      314,  252,  831,  854, 1244,  278,  119,  316,  872,  282,
      332,  898,  296,  334,   97,  916,  335,  934,  298, 1244,
      324,   57,  350,  960,  351,  986,  339,  353, 1010,  352,
      368, 1036,  365,  369, 1057,  374,  354, 1081,  389,  392,
     1104,  393,  407,  419,  421, 1125,  403,  409,  437, 1244,
     1149, 1153, 1157, 1161, 1165, 1169, 1173, 1175, 1179, 1183,

     1187, 1191, 1195, 1197, 1201, 1205, 1209, 1213, 1215, 1219,
     1223, 1227, 1231, 1235, 1239
    } ;

static yyconst short int yy_def[216] =
    {   0,
      191,  191,  190,  192,  190,  193,  192,  192,  192,  193,
      190,  190,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  194,  192,  192,  195,  192,  192,  196,  195,  192,
      192,  196,  197,  198,  196,  192,  192,  197,  198,  196,
      192,  192,  197,  198,   50,  192,  192,  197,  198,   50,
      192,  192,  197,  198,   50,  199,  200,  197,  198,  201,
      202,  200,  203,  204,  200,  205,  206,  201,  205,  206,
      192,  201,  207,  202,  203,  204,  200,  190,  205,  193,
      206,  201,  207,  208,  209,  207,  203,  204,   87,  205,

      206,   92,  208,  209,  207,  203,  204,   87,  205,  206,
       92,  208,  209,  105,  203,  204,   87,  205,  206,   92,
      208,  209,  105,  203,  204,  210,  205,  206,   92,  208,
      209,  105,  211,  212,  210,  211,  212,  192,  210,  205,
      206,  208,  209,  213,  190,  211,  193,  212,  210,  214,
      215,  213,  214,  215,  192,  213,  211,  212,  149,  190,
      214,  193,  215,  213,  211,  212,  149,  214,  215,  164,
      211,  212,  149,  214,  215,  164,  211,  212,  149,  214,
      215,  164,  211,  212,  214,  215,  164,  214,  215,    0,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,

      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190
    } ;

static yyconst short int yy_nxt[1273] =
    {   0,
      190,    5,    6,    5,    6,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,    7,   10,    7,   19,
       13,   16,   22,   10,    8,   18,    8,   25,   14,   15,
       17,   24,   10,   23,   20,   10,   21,   10,   10,   26,
       10,   30,   10,   32,   10,   10,   10,   28,   10,   10,
       27,   10,   10,   34,   31,   10,   53,   37,  190,   41,
       29,   10,   47,   10,   58,   52,   33,    9,   36,   10,
        9,    9,    9,    9,    9,   40,   10,    9,   38,    9,
       43,   44,   51,    9,    9,   10,   46,   10,   10,   43,
       67,   62,   10,   10,   57,   10,   10,   45,    9,   10,

       10,    9,   38,    9,   43,   44,   49,    9,    9,   45,
       43,   56,   48,   10,   10,   60,   97,   42,   63,   61,
      190,   45,   43,   44,  106,    9,    9,   54,   45,   10,
       66,   65,   48,   48,   88,   68,   42,   45,   76,   50,
       43,   44,   70,    9,    9,   42,   73,   89,   88,   10,
       10,   79,   85,   10,   10,   90,   79,   50,  115,   10,
       90,   89,   85,   86,   88,   55,   43,  133,   91,   10,
       10,   73,  103,   91,   10,   10,   79,  100,  130,   10,
       90,   94,  112,   54,   10,   10,   88,  112,   98,  103,
      121,   59,   43,  101,   75,   10,   10,   82,  104,  100,

      108,  190,   72,  111,   88,   78,   82,  109,   94,   49,
       75,   10,   10,  117,   78,   64,   43,   89,   72,   10,
       10,   82,   96,  118,  120,  113,   97,   75,  123,   78,
       93,   85,  126,   49,  124,   72,   69,    9,   88,   10,
        9,    9,    9,    9,   73,   74,   88,    9,    9,   96,
       82,   89,  132,  103,  127,  129,  142,   93,   78,   89,
      145,   75,   43,   96,  140,   10,   10,  145,  144,   88,
      103,   93,   10,  146,  136,  150,   85,   10,  147,   49,
      146,   53,   89,  145,   77,   79,   80,  160,    9,   81,
       48,  148,  190,   10,  136,   12,  157,   10,  147,   11,

      161,  160,   82,    9,   10,   10,    9,   83,    9,   73,
       74,  148,    9,    9,  161,   79,  139,  136,   10,   90,
       10,  147,  167,  190,  135,  190,   75,   73,   74,  160,
        9,    9,   91,  153,  158,  153,   10,  162,   10,  162,
      145,  190,  168,  190,   87,   79,   80,  190,    9,   81,
      163,  153,  163,  157,   10,  162,  145,  139,  160,  145,
      173,  165,   82,   79,   80,  135,    9,   81,  169,  146,
      156,  168,  146,  145,  160,  171,  176,  183,  152,  174,
       92,   94,   95,  139,    9,    9,  146,  161,  179,  177,
      190,  135,  156,  180,  190,  182,  190,  160,   96,    9,

      152,   10,    9,   83,    9,   73,   74,  139,    9,    9,
      161,  156,  145,  185,  160,  135,  187,  190,  190,  152,
      136,  156,   87,   10,  147,  146,  160,  161,  190,  152,
       99,   79,   80,  190,    9,   81,  190,  148,  153,  161,
      190,   10,  162,  190,  188,  190,  190,  190,   92,  190,
      190,  190,  190,  190,  190,  163,  102,   94,   95,  190,
        9,    9,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,   96,   94,   95,  190,    9,    9,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  105,   73,  190,  190,   10,   10,  190,  190,

      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
       98,  190,  190,  190,  190,  190,  190,  190,  107,   79,
      190,  190,   10,   90,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  101,  190,  190,  190,
      190,  190,  190,  190,  110,   94,   95,  190,    9,    9,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  105,  190,  190,  190,  190,  190,  190,  190,
      114,   73,  190,  190,   10,   10,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,   86,  190,
      190,  190,  190,  190,  116,   79,  190,  190,   10,   90,

      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,   91,  190,  190,  190,  190,  190,  119,   94,
      190,  190,   10,   10,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  113,  190,  190,  190,
      190,  190,  190,  190,  122,   73,  190,  190,   10,   10,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,   86,  190,  190,  125,   79,  190,  190,   10,
       90,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,   91,  190,  190,  128,   94,  190,  190,
       10,   10,  190,  190,  190,  190,  190,  190,  190,  190,

      190,  190,  190,  190,  104,  190,  190,  190,  190,  190,
      131,   73,  190,  190,   10,   10,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,   86,  190,
      190,  190,  190,  134,  136,  137,  190,    9,  138,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  139,   79,  190,  190,   10,   90,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,   91,
      190,  190,  190,  190,  141,   94,  190,  190,   10,   10,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  104,  190,  190,  143,  136,  137,  190,    9,

      138,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  139,  136,  137,  190,    9,  138,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  149,   94,  190,  190,   10,   10,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  104,
      190,  190,  190,  190,  151,  153,  154,  190,    9,  155,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  156,  136,  137,  190,    9,  138,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      149,  190,  190,  190,  190,  190,  190,  190,  159,  153,

      154,  190,    9,  155,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  156,  153,  154,  190,
        9,  155,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  164,  136,  190,  190,   10,  147,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  158,  190,  190,  190,  190,  190,  190,  190,
      166,  153,  154,  190,    9,  155,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  164,  190,
      190,  190,  190,  190,  190,  190,  170,  136,  190,  190,
       10,  147,  190,  190,  190,  190,  190,  190,  190,  190,

      190,  190,  190,  190,  148,  190,  190,  190,  190,  190,
      172,  153,  190,  190,   10,  162,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  169,  190,
      190,  190,  190,  190,  190,  190,  175,  136,  190,  190,
       10,  147,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  148,  190,  190,  178,  153,  190,
      190,   10,  162,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  163,  190,  190,  190,  190,
      190,  181,  136,  190,  190,   10,  147,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  148,

      190,  190,  190,  190,  184,  153,  190,  190,   10,  162,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  163,  190,  190,  186,  153,  190,  190,   10,
      162,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  163,  190,  190,  190,  190,  189,    4,
        4,    4,    4,    9,  190,    9,    9,   10,   10,   10,
       10,   35,  190,   35,   35,   39,  190,   39,   39,   42,
       42,   42,   42,   43,   43,   44,   44,   44,   44,   71,
      190,   71,   71,   72,   72,   72,   72,   78,   78,   78,
       78,   84,  190,   84,   84,   73,   73,   74,   74,   74,

       74,   79,   79,  190,   79,   80,   80,   80,   80,   93,
       93,   93,   93,   94,   94,   95,   95,   95,   95,  135,
      135,  135,  135,  136,  136,  190,  136,  137,  137,  137,
      137,  152,  152,  152,  152,  153,  153,  190,  153,  154,
      154,  154,  154,    3,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190
    } ;

static yyconst short int yy_chk[1273] =
    {   0,
        0,    1,    1,    2,    2,    7,    8,   13,   15,   17,
       14,   21,   16,   18,   20,   22,    1,   19,    2,   16,
        7,   13,   19,   23,    1,   15,    2,   22,    8,    8,
       14,   21,   24,   20,   17,   25,   18,   26,   28,   23,
       27,   27,   29,   29,   30,   31,   33,   25,   34,   37,
       24,   41,   47,   31,   28,   36,   53,   34,  162,   37,
       26,   40,   41,   46,   53,   47,   30,   32,   33,   32,
       32,   32,   32,   32,   35,   36,   35,   35,   35,   35,
       38,   38,   46,   38,   38,   52,   40,   57,   62,   44,
       62,   57,   44,   44,   52,   51,   56,   38,   39,  155,

       39,   39,   39,   39,   42,   42,   44,   42,   42,   55,
       49,   51,   58,   49,   49,   55,   97,   55,   58,   56,
      147,   42,   45,   45,   97,   45,   45,   49,   60,   61,
       61,   60,   63,   68,   76,   63,   60,   65,   68,   45,
       50,   50,   65,   50,   50,   65,   74,   76,   79,   74,
       74,   77,  106,  138,   77,   77,   80,   50,  106,   80,
       80,   79,  124,   74,   89,   50,   54,  124,   77,   54,
       54,   86,  121,   80,   86,   86,   91,   89,  121,   91,
       91,   95,  112,   54,   95,   95,  100,  103,   86,   94,
      112,   54,   59,   91,   99,   59,   59,  102,   95,  100,

       99,   90,   99,  102,  109,  102,  129,  100,  104,   59,
      108,  104,  104,  108,  129,   59,   64,  109,  108,   64,
       64,  111,  114,  109,  111,  104,   85,  117,  114,  111,
      114,  115,  117,   64,  115,  117,   64,   66,  118,   66,
       66,   66,   66,   66,   67,   67,  127,   67,   67,  123,
      120,  118,  123,  130,  118,  120,  130,  123,  120,  127,
      133,   67,   69,  132,  127,   69,   69,  136,  132,  140,
      142,  132,   81,  133,  134,  142,   73,  134,  134,   69,
      136,   48,  140,  146,   69,   70,   70,  150,   70,   70,
       43,  134,   10,    9,  137,    6,  146,  137,  137,    5,

      150,  153,   70,   71,    4,   71,   71,   71,   71,   72,
       72,  137,   72,   72,  153,  141,  159,  148,  141,  141,
      148,  148,  159,    3,  159,    0,   72,   75,   75,  161,
       75,   75,  141,  151,  148,  154,  151,  151,  154,  154,
      157,    0,  161,    0,   75,   78,   78,    0,   78,   78,
      151,  163,  154,  157,  163,  163,  165,  167,  168,  177,
      167,  157,   78,   82,   82,  167,   82,   82,  163,  165,
      170,  168,  177,  171,  174,  165,  170,  177,  170,  168,
       82,   83,   83,  173,   83,   83,  171,  174,  173,  171,
        0,  173,  176,  174,    0,  176,    0,  180,   83,   84,

      176,   84,   84,   84,   84,   87,   87,  179,   87,   87,
      180,  182,  183,  180,  188,  179,  182,    0,    0,  182,
      184,  187,   87,  184,  184,  183,  185,  188,    0,  187,
       87,   92,   92,    0,   92,   92,    0,  184,  189,  185,
        0,  189,  189,    0,  185,    0,    0,    0,   92,    0,
        0,    0,    0,    0,    0,  189,   92,   93,   93,    0,
       93,   93,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   93,   96,   96,    0,   96,   96,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   96,   98,    0,    0,   98,   98,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       98,    0,    0,    0,    0,    0,    0,    0,   98,  101,
        0,    0,  101,  101,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  101,    0,    0,    0,
        0,    0,    0,    0,  101,  105,  105,    0,  105,  105,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  105,    0,    0,    0,    0,    0,    0,    0,
      105,  107,    0,    0,  107,  107,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  107,    0,
        0,    0,    0,    0,  107,  110,    0,    0,  110,  110,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  110,    0,    0,    0,    0,    0,  110,  113,
        0,    0,  113,  113,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  113,    0,    0,    0,
        0,    0,    0,    0,  113,  116,    0,    0,  116,  116,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  116,    0,    0,  116,  119,    0,    0,  119,
      119,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  119,    0,    0,  119,  122,    0,    0,
      122,  122,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  122,    0,    0,    0,    0,    0,
      122,  125,    0,    0,  125,  125,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  125,    0,
        0,    0,    0,  125,  126,  126,    0,  126,  126,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  126,  128,    0,    0,  128,  128,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  128,
        0,    0,    0,    0,  128,  131,    0,    0,  131,  131,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  131,    0,    0,  131,  135,  135,    0,  135,

      135,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  135,  139,  139,    0,  139,  139,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  139,  143,    0,    0,  143,  143,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  143,
        0,    0,    0,    0,  143,  144,  144,    0,  144,  144,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  144,  149,  149,    0,  149,  149,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      149,    0,    0,    0,    0,    0,    0,    0,  149,  152,

      152,    0,  152,  152,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  152,  156,  156,    0,
      156,  156,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  156,  158,    0,    0,  158,  158,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  158,    0,    0,    0,    0,    0,    0,    0,
      158,  164,  164,    0,  164,  164,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  164,    0,
        0,    0,    0,    0,    0,    0,  164,  166,    0,    0,
      166,  166,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  166,    0,    0,    0,    0,    0,
      166,  169,    0,    0,  169,  169,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  169,    0,
        0,    0,    0,    0,    0,    0,  169,  172,    0,    0,
      172,  172,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  172,    0,    0,  172,  175,    0,
        0,  175,  175,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  175,    0,    0,    0,    0,
        0,  175,  178,    0,    0,  178,  178,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  178,

        0,    0,    0,    0,  178,  181,    0,    0,  181,  181,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  181,    0,    0,  181,  186,    0,    0,  186,
      186,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  186,    0,    0,    0,    0,  186,  191,
      191,  191,  191,  192,    0,  192,  192,  193,  193,  193,
      193,  194,    0,  194,  194,  195,    0,  195,  195,  196,
      196,  196,  196,  197,  197,  198,  198,  198,  198,  199,
        0,  199,  199,  200,  200,  200,  200,  201,  201,  201,
      201,  202,    0,  202,  202,  203,  203,  204,  204,  204,

      204,  205,  205,    0,  205,  206,  206,  206,  206,  207,
      207,  207,  207,  208,  208,  209,  209,  209,  209,  210,
      210,  210,  210,  211,  211,    0,  211,  212,  212,  212,
      212,  213,  213,  213,  213,  214,  214,    0,  214,  215,
      215,  215,  215,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  190
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./FOLDER_1_LEXER_User/User.lex"
#define INITIAL 0
#line 2 "./FOLDER_1_LEXER_User/User.lex"
/*************************/
/* GENERAL INCLUDE FILES */
/*************************/
#include <math.h>
#include <string.h>
#include <stdlib.h>

/*************************/
/* PROJECT INCLUDE FILES */
/*************************/
#include "User_ErrorMsg.h"
#include "User_Tokens.h"
#include "util.h"

/**************************/
/* CONTROL ERROR MESSAGES */
/**************************/
static int charPos=1;

/******************/
/* PROVIDE aaWRAP */
/******************/
int aawrap(void)
{
	charPos=1;
	return 1;
}

/**************************/
/* CONTROL ERROR MESSAGES */
/**************************/
static void adjust(void)
{
	User_ErrorMsg_tokPos = charPos;
	charPos += aaleng;
}

/***********/
/* YYSTYPE */
/***********/
YYSTYPE aalval;

/*****************/
/* UNIQUE PREFIX */
/*****************/
/********************/
/* COMMON REGEXP(s) */
/********************/
/***************/
/* PARENTHESES */
/***************/
/**********/
/* SPACES */
/**********/
/*******************/
/* LINE TERMINATOR */
/*******************/
/********/
/* USER */
/********/
/****************************/
/* FUNC WITH USER ATTRIBUTE */
/****************************/
/******/
/* ID */
/******/
/*********/
/* RULES */
/*********/
#line 797 "./FOLDER_1_LEXER_User/User_Lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 89 "./FOLDER_1_LEXER_User/User.lex"

#line 950 "./FOLDER_1_LEXER_User/User_Lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 191 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1244 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 90 "./FOLDER_1_LEXER_User/User.lex"
{
						FILE *fl;
						char *p = aatext+strlen("SYSCALL_DEFINE0(");
						char *q = strchr(p,',');
						char funcname[100];
						char filename[100];
						memset(funcname,0,sizeof(funcname));
						strncpy(funcname,p,q-p);
						User_ErrorMsg_Log("Please inline this mother fucker: %s",funcname);
						sprintf(filename,"/home/oren/GIT/llvm_apron_pass/Examples/INLINE_ME/FOLDER_8_INLINE_GANG/%s",funcname);
						fl = fopen("/home/oren/GIT/llvm_apron_pass/Examples/INLINE_ME/FOLDER_8_INLINE_GANG/funcname","w+t");
						fprintf(fl,"INLINE ME BABY!!!\n");
						fclose(fl);
						continue;
					}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "./FOLDER_1_LEXER_User/User.lex"
{
						FILE *fl;
						char *p = aatext+strlen("ssize_t ");
						char *q = strchr(p,'(');
						char funcname[100];
						char filename[100];
						memset(funcname,0,sizeof(funcname));
						strncpy(funcname,p,q-p);
						User_ErrorMsg_Log("Please inline this mother fucker: %s",funcname);
						sprintf(filename,"/home/oren/GIT/llvm_apron_pass/Examples/INLINE_ME/FOLDER_8_INLINE_GANG/%s",funcname);
						fl = fopen(filename,"w+t");
						fprintf(fl,"INLINE ME BABY!!!\n");
						fclose(fl);
						continue;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 120 "./FOLDER_1_LEXER_User/User.lex"
{
						FILE *fl;
						char *p = aatext+strlen("static ssize_t ");
						char *q = strchr(p,'(');
						char funcname[100];
						char filename[100];
						memset(funcname,0,sizeof(funcname));
						strncpy(funcname,p,q-p);
						User_ErrorMsg_Log("Please inline this mother fucker: %s",funcname);
						sprintf(filename,"/home/oren/GIT/llvm_apron_pass/Examples/INLINE_ME/FOLDER_8_INLINE_GANG/%s",funcname);
						fl = fopen(filename,"w+t");
						fprintf(fl,"INLINE ME BABY!!!\n");
						fclose(fl);
						continue;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 135 "./FOLDER_1_LEXER_User/User.lex"
{User_ErrorMsg_Log("%s", aatext); continue;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 136 "./FOLDER_1_LEXER_User/User.lex"
{User_ErrorMsg_Log("%s", aatext); continue;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 137 "./FOLDER_1_LEXER_User/User.lex"
{User_ErrorMsg_Log("%s", aatext); continue;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 138 "./FOLDER_1_LEXER_User/User.lex"
{User_ErrorMsg_Log("%s", aatext); continue;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 139 "./FOLDER_1_LEXER_User/User.lex"
{User_ErrorMsg_Log("%s", aatext); continue;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 141 "./FOLDER_1_LEXER_User/User.lex"
ECHO;
	YY_BREAK
#line 1120 "./FOLDER_1_LEXER_User/User_Lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 191 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 191 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 190);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p = yytext_ptr + offset;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 141 "./FOLDER_1_LEXER_User/User.lex"
